#!/bin/python3

import os
import sys
import difflib
import subprocess

PROFILE = "hyprland"


def main():
    if len(sys.argv) == 1:
        print("Error: provide arguments.")
        sys.exit(1)

    match " ".join(sys.argv[1:]):
        case "diff":
            diff()
        case "installable":
            print(get_installable(PROFILE, ""))
        case "installable aur":
            print(get_installable(PROFILE, "aur"))
        case "installable flatpak":
            print(get_installable(PROFILE, "flatpak"))
        case _:
            print("Error: arguments invalid.")


def diff():
    selected = PROFILES[PROFILE] + AUR
    selected.sort()
    selected += FLATPAKS

    installed = (
        subprocess.run(
            ["pacman", "-Qeq"], capture_output=True, text=True
        ).stdout.split()
        + subprocess.run(
            ["flatpak", "list", "--app", "--columns=application"],
            capture_output=True,
            text=True,
        ).stdout.split()
    )

    diff = list(difflib.ndiff(selected, installed))
    for line in diff:
        if line.startswith(("+", "-")):
            print(line)


def get_installable(profile, type):
    return_str = ""

    if type == "":
        for pkg in PROFILES.get(profile, []):
            return_str += " " + pkg

    if type == "aur":
        for pkg in AUR:
            return_str += " " + pkg

    if type == "flatpak":
        for pkg in FLATPAKS:
            return_str += " " + pkg

    return return_str


FLATPAKS = [
    "be.alexandervanhee.gradia",
    "com.usebottles.bottles",
    "dev.mufeed.Wordbook",
    "dev.vencord.Vesktop",
    "garden.jamie.Morphosis",
    "it.mijorus.gearlever",
]

AUR = [
    "code-marketplace",
    "ungoogled-chromium-bin",
    "yay"
]

BASIC = [
    "ascii",
    "base",
    "base-devel",
    "bash-language-server",
    "btop",
    "btrfs-progs",
    "bun",
    "clang",
    "cmake",
    "curl",
    "delve",
    "docker",
    "docker-compose",
    "dosfstools",
    "exfatprogs",
    "fastfetch",
    "fd",
    "firejail",
    "fuse2",
    "fzf",
    "git",
    "git-delta",
    "github-cli",
    "go",
    "gofumpt",
    "gopls",
    "gptfdisk",
    "grub",
    "intel-ucode",
    "jq",
    "keyd",
    "libnewt",
    "linux",
    "linux-firmware",
    "lua-language-server",
    "man-db",
    "neovim",
    "networkmanager",
    "nodejs",
    "npm",
    "ntfs-3g",
    "openconnect",
    "openssh",
    "openvpn",
    "pacman-contrib",
    "papirus-icon-theme",
    "php",
    "pnpm",
    "prettier",
    "proton-vpn-cli",
    "pyright",
    "python-pip",
    "rclone",
    "reflector",
    "ripgrep",
    "ruff",
    "rust",
    "sbctl",
    "shfmt",
    "sudo",
    "tailscale",
    "taskwarrior-tui",
    "tmux",
    "tree",
    "tree-sitter-cli",
    "typescript",
    "typescript-language-server",
    "udisks2",
    "ufw",
    "unzip",
    "usbutils",
    "uv",
    "valgrind",
    "vscode-css-languageserver",
    "vscode-html-languageserver",
    "vscode-json-languageserver",
    "wget",
    "zip",
    "zram-generator",
    "zsh",
]

if not os.path.exists("/sys/firmware/uefi"):
    BASIC.append("efibootmgr")

DESKTOP = [
    "accountsservice",
    "adw-gtk-theme",
    "amberol",
    "android-tools",

    "audacity",
    "bluez",
    "bluez-utils",
    "code",
    "dmidecode",
    "dnsmasq",
    "drawio-desktop",
    "eartag",
    "ffmpeg",
    "firefox",
    "flatpak",
    "flatpak-builder",
    "flatseal",
    "gimp",
    "gnome-calculator",
    "gnome-clocks",
    "gnome-disk-utility",
    "gnome-keyring",
    "gnome-sound-recorder",
    "gnome-tweaks",
    "gst-plugins-bad",
    "gvfs-mtp",
    "imagemagick",
    "kitty",
    "libreoffice-fresh",
    "loupe",
    "mpv",
    "mpv-mpris",
    "mupdf",
    "nautilus",
    "noto-fonts",
    "noto-fonts-cjk",
    "noto-fonts-emoji",
    "noto-fonts-extra",
    "obs-studio",
    "opencode",
    "pdfarranger",
    "pdftk",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "polkit-gnome",
    "pyside6",
    "python",
    "python-service-identity",
    "qbittorrent",
    "qemu-full",
    "scrcpy",
    "seahorse",
    "shotcut",
    "snapshot",
    "sof-firmware",
    "solanum",
    "spice-vdagent",
    "swtpm",
    "syncplay",
    "ttf-jetbrains-mono-nerd",
    "virt-manager",
    "vulkan-icd-loader",
    "vulkan-intel",
    "wireplumber",
    "yt-dlp",
    "zathura",
    "zathura-pdf-mupdf",
    "zed",
]

PROFILES = {
    "hyprland": [
        "bluetui",
        "breeze",
        "brightnessctl",
        "cliphist",
        "grim",
        "hypridle",
        "hyprland",
        "hyprlock",
        "hyprpaper",
        "hyprpicker",
        "mako",
        "pavucontrol",
        "power-profiles-daemon",
        "qt5-wayland",
        "qt5ct",
        "qt6-wayland",
        "qt6ct",
        "rofi",
        "rofi-emoji",
        "slurp",
        "uwsm",
        "waybar",
        "wev",
        "wl-clip-persist",
        "wl-clipboard",
        "xdg-desktop-portal-gtk",
        "xdg-desktop-portal-hyprland",
        "xdg-user-dirs",
    ]
    + BASIC
    + DESKTOP,
}

if __name__ == "__main__":
    main()
