[tmux]
config/tmux -> ~/.config/tmux

[zathura]
config/zathura -> ~/.config/zathura

[git]
gitconfig -> ~/.gitconfig

[hypr]
config/hypr -> ~/.config/hypr

[foot]
config/foot -> ~/.config/foot

[mako]
config/mako -> ~/.config/mako

[mpv]
config/mpv -> ~/.config/mpv

[rofi]
config/rofi -> ~/.config/rofi

[waybar]
config/waybar -> ~/.config/waybar

[yt-dlp]
config/yt-dlp -> ~/.config/yt-dlp

[neovim]
config/nvim -> ~/.config/nvim

[zed]
config/zed -> ~/.config/zed

[zsh]
config/zsh -> ~/.config/zsh
zshenv -> ~/.zshenv

[wallpaper]
local-share/wall.png ->  ~/.local/share/wall.png

[scripts]
local-bin -> ~/.local/bin

[keyd]
etc/keyd -> /etc/keyd

[libvirt]
etc/libvirt/ -> /etc/libvirt

[faillock]
etc/security -> /etc/security
