[herdr]
config/herdr -> ~/.config/herdr

[copilot]
copilot -> ~/.copilot

[opencode]
config/opencode -> ~/.config/opencode

[pomo]
config/pomo -> ~/.config/pomo

[zathura]
config/zathura -> ~/.config/zathura

[git]
gitconfig -> ~/.gitconfig

[btop]
config/btop -> ~/.config/btop

[vscode]
config/Code - OSS -> ~/.config/Code - OSS

[fastfetch]
config/fastfetch -> ~/.config/fastfetch

[ghostty]
config/ghostty -> ~/.config/ghostty

[hypr]
config/hypr -> ~/.config/hypr

[kitty]
config/kitty -> ~/.config/kitty

[mako]
config/mako -> ~/.config/mako

[mpv]
config/mpv -> ~/.config/mpv

[neovide]
config/neovide -> ~/.config/neovide

[neovim]
config/nvim -> ~/.config/nvim

[rofi]
config/rofi -> ~/.config/rofi

[tmux]
config/tmux -> ~/.config/tmux

[waybar]
config/waybar -> ~/.config/waybar

[yt-dlp]
config/yt-dlp -> ~/.config/yt-dlp

[zed]
config/zed -> ~/.config/zed

[zsh]
config/zsh -> ~/.config/zsh
zshenv -> ~/.zshenv

[wallpaper]
local-share/wall.png ->  ~/.local/share/wall.png

[default apps]
config/mimeapps.list -> ~/.config/mimeapps.list

[custom scripts]
local-bin -> ~/.local/bin
