general {
    hide_cursor = true
}

auth {
    pam {
        enabled = true
    }
}

animations {
    enabled = false
}

background {
    monitor =
    path = ~/.local/share/wall.png
}

input-field {
    monitor =

    fade_on_empty = false

    size = 290, 45
    outline_thickness = 2
    dots_size = 0.2

    outer_color = 0xff888888
    inner_color = 0xff000000

    font_color = 0xffffffff
    font_family = JetBrainsMono Nerd Font

    rounding = 0

    check_color = 0xff25be6a
    fail_color = 0xffff0000
    fail_text = Authentication Failed
    capslock_color = 0xffffa500
    numlock_color = 0xff888888
    bothlock_color = 0xffffa500

    halign = center
    valign = center
}
