$gray1 = 0xff2e3440
$gray2 = 0xff3b4252
$gray3 = 0xff434c5e
$gray4 = 0xff4c566a

$white0 = 0xffc0c8d8
$white1 = 0xffd8dee9
$white3 = 0xffeceff4

$blue = 0xff88c0d0
$red = 0xffbf616a
$orange = 0xffd08770

$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
    ignore_empty_input = true
    text_trim = true
    immediate_render = true
}

auth {
    pam {
        enabled = true
    }
}

animations {
    enabled = true
}

background {
    monitor =
    path =
    color = $gray1
}

label {
    monitor =

    text = cmd[update:1000] date +"%H:%M"
    color = $white3

    font_size = 72
    font_family = $font

    position = 0, 128

    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:60000] date +"%A, %e %B"
    color = $white0

    font_size = 14
    font_family = $font

    position = 0, 72

    halign = center
    valign = center
}

input-field {
    monitor =

    fade_on_empty = false
    hide_input = false

    size = 290, 45
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true

    outer_color = $gray3
    inner_color = $gray2

    font_color = $white1
    font_family = $font

    rounding = 0

    placeholder_text = <span foreground="##4c566a">$USER</span>

    check_color = $blue
    checking_text = ...

    fail_color = $red
    fail_text = <span foreground="##eceff4">$FAIL ($ATTEMPTS)</span>
    fail_timeout = 1500

    capslock_color = $orange
    numlock_color = $gray3
    bothlock_color = $orange

    halign = center
    valign = center
}

label {
    monitor =

    text = $LAYOUT
    color = $gray4

    font_size = 12
    font_family = $font

    position = 0, -52

    halign = center
    valign = center
}
