general {
    hide_cursor = true
}

auth {
    pam {
        enabled = true
    }
}

animations {
    enabled = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =

    size = 290, 45
    outline_thickness = 2
    dots_size = 0.2

    outer_color = 0xff535353
    inner_color = 0xff161616

    font_color = 0xfff2f4f8
    font_family = JetBrainsMono Nerd Font Mono

    placeholder_text = Password

    rounding = 10

    check_color = 0xff25be6a
    fail_color = 0xffee5396
    fail_text = Authentication Failed
    capslock_color = 0xff3ddbd9
    numlock_color = 0xfff2f4f8
    bothlock_color = 0xffebcb8b

    halign = center
    valign = center
}
