onSessionEnd: "ask"

asciiArt:
  enabled: true

  font: ansiShadow

  color: "none"

work:
  duration: 45m
  title: work session

  notification:
    enabled: true
    urgent: true
    title: Pomo
    message: Work Finished

  then:
    - [paplay, /usr/share/sounds/freedesktop/stereo/complete.oga]

break:
  duration: 15m

  notification:
    enabled: true
    urgent: true
    title: Pomo
    message: Break Finished

  then:
    - [paplay, /usr/share/sounds/freedesktop/stereo/complete.oga]

longBreak:
  enabled: false
