map alt+t new_tab_with_cwd
map alt+w close_tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4

enable_audio_bell no

font_size 12.0
font_family JetBrainsMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto

cursor #d4be98
foreground #d4be98
background #282828
selection_foreground #282828
selection_background #d4be98
color0 #3c3836
color1 #ea6962
color2 #a9b665
color3 #d8a657
color4 #7daea3
color5 #d3869b
color6 #89b482
color7 #d4be98
color8 #3c3836
color9 #ea6962
color10 #a9b665
color11 #d8a657
color12 #7daea3
color13 #d3869b
color14 #89b482
color15 #d4be98

tab_bar_min_tabs 1
tab_title_template "{tab.active_exe}"
tab_bar_edge bottom
tab_bar_style separator
tab_separator " "
tab_bar_background #32302f
active_tab_font_style normal
active_tab_foreground #d4be98
active_tab_background #32302f
inactive_tab_font_style normal
inactive_tab_foreground #7c6f64
inactive_tab_background #32302f
