font_family JetBrainsMono Nerd Font Mono
font_size 12

# window_padding_width 10
window_padding_width 5 10 5 10

clear_all_shortcuts yes
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+equal increase_font_size
map ctrl+shift+minus decrease_font_size


# BEGIN_KITTY_THEME
# Carbonfox
include current-theme.conf
# END_KITTY_THEME
