font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

tab_bar_style    hidden
clear_all_shortcuts yes

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+plus  change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0
map ctrl+shift+0     change_font_size all 0

foreground            #d8dee9
background            #2e3440
selection_foreground  #d8dee9
selection_background  #434c5e
cursor                #d8dee9
cursor_text_color     #2e3440

color0                #3b4252
color1                #bf616a
color2                #a3be8c
color3                #ebcb8b
color4                #88c0d0
color5                #b48ead
color6                #8fbcbb
color7                #e5e9f0
color8                #4c566a
color9                #c5727a
color10               #b1c89d
color11               #efd49f
color12               #81a1c1
color13               #be9db8
color14               #9fc6c5
color15               #eceff4
