# Functionality
set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on

set -g mouse on

set -g focus-events on

# Appearance
set -g status-style "bg=default,fg=default"
set -g pane-active-border-style "fg=blue"

set -g status-left ""
set -g status-right "#[fg=blue]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#(whoami)@#h "

set -g window-status-current-format '#[bg=magenta,fg=black,bold] #I:#W* '
set -g window-status-format ' #I:#W- '
set -g window-status-separator ''

# Keymaps
set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind t choose-tree -swZ

bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
