# Functionality
set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on

set -g mouse on

# Keymaps
set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind t choose-tree -swZ

bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
